(defpackage sanitize
  (:use :cl)
  (:import-from
   :closer-mop
   :standard-class
   :standard-direct-slot-definition
   :standard-effective-slot-definition
   :direct-slot-definition-class
   :effective-slot-definition-class
   :slot-definition-name
   :validate-superclass)
  (:import-from
   :cl-comp
   :filter-slots-by-type)
  (:import-from
   :xml.parse
   :*mode*
   :stray-closing-tag-error
   :class-not-found-error
   :slot-not-found-error
   :tag-mismatch-error
   :invalid-xml-character-error
   :restricted-xml-character-error
   :remove-character
   :assign-text-node
   :close-node
   :ignore-missing-slot
   :parse-document
   :serialize
   :text-node
   :element-class
   :dom-node
   :class->element
   :attribute->slot
   :xml-direct-slot-definition
   :slot-definition-attribute)
  (:import-from
   :html.parse
   :document-node
   :*html-element-class-map*
   :read-fragment)
  (:import-from
   :quri
   :uri
   :uri-path
   :uri-scheme)
  (:import-from
   :stw.util
   :ensure-list
   :awhen
   :self
   :whitespacep)

  (:export
   :define-whitelist
   :whitelist
   :whitelist-rule
   :whitelist-parser
   :sanitize

   ;;modes
   :text-only
   :basic
   :restricted
   :relaxed))
